### ISSUE TITLE
Compile literature on UHI

### ISSUE THREAD

**Issue by maning** [teresapeteti/UHI-Visakhapatnam#1]
@marthaleena

**Comment by Marthaleena** [comment]
I explored all the research papers related to Urban Heat Island determination using Remote Sensing.There were different sources found and each of them followed a unique process to determine.I have taken preference to projects concerned in India.I have listed all of them 

1.**Remote sensing Based Assessment of Urban Heat Island Phenomenon in Nagpur Metropolitan Area**(https://www.ripublication.com/irph/ijict_spl/ijictv4n11spl_08.pdf):
In this paper the UHI was determined from NDVI.Firstly,LST was determined and then NDVI was calculated.Based on it a Scatterplot was drawn showing their relation.
It is quite simple with basic classification,LST and NDVI. It is very helpful to determine the LST values from bands as it is clearly explained.
![image](https://user-images.githubusercontent.com/28780397/32936811-cd4fb028-cb9b-11e7-8cf4-3bd83979693f.png)

2.**Study of Influence of Land Cover on Urban Heat Islands in Pune Using Remote Sensing**(http://www.iosrjournals.org/iosr-jmce/papers/sicete%28civil%29-volume4/44.pdf):
In this paper the analysis was done based on Land cover changes over the years.A linear equation is derived from landcover and temperature 

- Supervised classification 
- Reclassification to remove distortion
- Change Detection between different timescales(1992,1999,2006)
-Transformation-Derivation of LST-The corresponding temperatures for all data derived from ETM
thermal bands were converted to degree Celsius. 
![image](https://user-images.githubusercontent.com/28780397/32937308-f8ce8646-cb9d-11e7-8988-779c33813bc0.png)

3. **Assessment of Urban Heat Island through Remote Sensing in Nagpur Urban Area Using Landsat 7 ETM+ Satellite Images**(http://waset.org/publications/10007350/assessment-of-urban-heat-island-through-remote-sensing-in-nagpur-urban-area-using-landsat-7-etm-satellite-images):
Similar to other papers LULC was the factor to determine UHI .Supervised classification,LST 
 with Change detection.Analysis was done based ground knowledge as points for reference to draw conclusions about the distribution.
![image](https://user-images.githubusercontent.com/28780397/32937487-c9b3f91c-cb9e-11e7-9d75-adafff2431a3.png)

4.**Assessment of Urban Heat Island Using Remotely Sensed Imagery over Greater Cairo, Egypt**(https://file.scirp.org/pdf/ARS_2015030315125157.pdf):
The Area of Interest is Cairo of Egypt, apart from that it had seasonal variations included with mean ,median  of temperatures with time differences.
![image](https://user-images.githubusercontent.com/28780397/32938587-b355142c-cba2-11e7-9e01-6f006854116e.png)

**Comment by Marthaleena** [comment]
There are other factors which influence the UHI ,the following are the research papers which focused themselves on few of them.

1. **Assessment of Urban Heat Island (UHI) using Remote Sensing and GIS**(https://globaljournals.org/GJHSS_Volume16/1-Assessment-of-Urban.pdf):
In this paper the factors taken are Vegetation density and Urbanisation parameters which include
air pollution and population.The Air quality was analysed based on amounts of Sulphur Dioxide,Carbon Monoxide,Particulate Matter and Nitrogen Dioxide.The objectives of the paper are very clear
• To analyze the relationship between LST and Vegetation Density in urban area.
• Evaluate the connection between LST and Population Density and also Air Quality(Parameters included CO,SO2,NO2,PM's)
![image](https://user-images.githubusercontent.com/28780397/32977662-df7d2002-cc57-11e7-948f-09bb06a96ca4.png)

2. **Mapping of micro-urban heat islands and land cover changes: a case in Chennai City, India.**(https://www.researchgate.net/publication/233997577_Mapping_of_micro-urban_heat_islands_and_land_cover_changes_a_case_in_Chennai_City_India):
In area of study is Chennai a coastal city similar to Visakhapatnam, LULC was the factor used for detemining UHI

3. **Monitoring Spatial Patterns of Land Surface Temperature and Urban Heat Island for Sustainable Megacity:A Case Study of Mumbai, India, Using Landsat TM Data**:(http://journals.sagepub.com/doi/pdf/10.1177/0975425315619722):
In this paper the relationship between LST,NDVI,NDBI was determined.Similar to NDVI,NDBI could be determined using MIR and NIR bands.

4. **Satellite Observation of Urban Heat Island Effect** (http://www.cge.uevora.pt/GCGW/presentations/172-236-1-DR.pdf):
This paper could be used as a reference to use TIR Band of ASTER data for LST.
![image](https://user-images.githubusercontent.com/28780397/32978444-6f10f454-cc68-11e7-9414-2408e51c3527.png)

These are some of the papers which would be helpful  for our paper.Further research has to be done for getting data or availability of data by browsing through satellites data availability to extend factors affecting UHI.
cc: @maning @teresapeteti @bhavana-naga

**Comment by maning** [comment]
Great summary @Marthaleena, it seems to me that research around this topic in India focused mostly on LULC in relation to surface temperature.  However, very little temporal granularity was done.  Most studies have either 2 dates or multi-year spanning 5-7 year interval.  

Per our discussion, let's focus on **building a 30 year annual surface temperature data that will provide better temporal granularity for understanding temparature changes in Vizag.**
