### ISSUE TITLE
Inventory of Landsat TM/ETM+ for 1996-2016

### ISSUE THREAD

**Issue by maning** [teresapeteti/UHI-Visakhapatnam#3]
@teresapeteti 
Use this site for inventory: https://libra.developmentseed.org/

**Comment by teresapeteti** [comment]
**I tried to find the available Landsat data for 1996-2016.
Checked all available data, and filtered it to less 10% cloud cover.
Below is the list of years and the months in them where we can find less than 10% cloud cover.**

**(Landsat 8)**
2016: November; October; September; May; March; February; January

2015: December; November; October; March; February; January

2014: December; October; May; April; March; February; January

2013: December; November; October; August(LS 8)
          December; November; May; April; March; February; January(LS 7)

**(Landsat 7)**
2012: May; March 

2011: December; November; October; March; February

2010: December; May; April; March; February; January 

2009: December; November; October; May; April; March; February 

2008: December; October; May; April; March; January

2007: November; May; April; March; February

2006: December; November; October; March; February; January

2005: March; February

2004: December; November; September; August; May; March; February; January

2003: November; October; March; January

2002: December; November; May; March

2001: December; September; May; March; January

2000: December; October; April

1999: October

**(Landsat 5 TM)**
1998: February

1997: November; October; September; May; March; February; January

1996: November; April; March; February; January 

Month | Years with 👍 data|
|----|----|
January| ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ 
February|⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ 
March|⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ 
April| ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️  
May|⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ 
June| 😢 
July|😢 
August| ⭐️ ⭐️ 
September|⭐️ ⭐️ ⭐️ ⭐️ 
October|⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ 
November|⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️⭐️
December|⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️⭐️

**Upon analysis, the data in March is available in almost every year with <10% cloud cover.
If we consider only cloud cover as a parameter to select data, then March can be selected to make analysis through 20 years.**

**Ps: Had trouble in finding data for the year 1998.**

**Comment by maning** [comment]
Great summary!  It seems we have enough data for March to cover annual time slice.  Next actions is to download and evaluate the data. @teresapeteti please cut a new ticket for data eval outlining steps of the evaluation process.   Things to consider are the following:

* L5 and L7/8 have different ground resolution.  For the thermal band, it's ~120 meters for L5 and ~60 m for L7/8 .  What do you think should be our common resolution to use?
* During our discussion, landuse change and potentially surface temperature changed dramatically during late 1990s up to 2000s in Vizag.  L7's [Scan line correction (SLC) failed May 2003](https://landsat.usgs.gov/what-landsat-7-etm-slc-data) as a result, all imagery taken after that have data gaps.  Do we have that problem for our AOI?  If so, how do we fill data gaps?  Do we need to merge two different imagery?
